# Generated by Django 4.0.2 on 2022-02-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
